# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Valentina_tools.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Tools(object):
    def setupUi(self, Tools):
        Tools.setObjectName("Tools")
        Tools.resize(610, 240)
        Tools.setStyleSheet("background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:0, y2:0, stop:0\n"
"rgba(81, 0, 200, 255), stop:0.427447 rgba(41, 61, 150, 235), stop:1 rgba(170, 79, 165, 255));\n"
"")
        self.centralwidget = QtWidgets.QWidget(Tools)
        self.centralwidget.setObjectName("centralwidget")
        self.comand_voice = QtWidgets.QLineEdit(self.centralwidget)
        self.comand_voice.setGeometry(QtCore.QRect(130, 10, 471, 21))
        self.comand_voice.setStyleSheet("background-color:rgb(150,150,150);\n"
"color:white;\n"
"border: none;\n"
"margin: 0px;\n"
"padding: 0px;\n"
"")
        self.comand_voice.setObjectName("comand_voice")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 111, 21))
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setStyleSheet("color:white;\n"
"background-color: rgba(50, 50, 50, 150);\n"
"border: none;\n"
"margin: 0px;\n"
"padding: 0px;\n"
"")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.way_file_tool = QtWidgets.QToolButton(self.centralwidget)
        self.way_file_tool.setGeometry(QtCore.QRect(580, 41, 21, 20))
        self.way_file_tool.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.way_file_tool.setStyleSheet("background-color: rgba(50, 50, 50, 150);\n"
"color:white;\n"
"border: none;\n"
"margin: 0px;\n"
"padding: 0px;")
        self.way_file_tool.setObjectName("way_file_tool")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 40, 91, 21))
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setStyleSheet("color:white;\n"
"background-color: rgba(50, 50, 50, 150);\n"
"border: none;\n"
"margin: 0px;\n"
"padding: 0px;\n"
"")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.way_file = QtWidgets.QLineEdit(self.centralwidget)
        self.way_file.setGeometry(QtCore.QRect(130, 40, 451, 21))
        self.way_file.setStyleSheet("background-color:rgb(150,150,150);\n"
"color:white;\n"
"border: none;\n"
"margin: 0px;\n"
"padding: 0px;\n"
"")
        self.way_file.setObjectName("way_file")
        self.check_way_file = QtWidgets.QCheckBox(self.centralwidget)
        self.check_way_file.setGeometry(QtCore.QRect(11, 40, 16, 21))
        self.check_way_file.setStyleSheet("background-color: rgba(50, 50, 50, 0);")
        self.check_way_file.setText("")
        self.check_way_file.setObjectName("check_way_file")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 70, 91, 21))
        self.label_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_3.setStyleSheet("color:white;\n"
"background-color: rgba(50, 50, 50, 150);\n"
"border: none;\n"
"margin: 0px;\n"
"padding: 0px;\n"
"")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.way_url = QtWidgets.QLineEdit(self.centralwidget)
        self.way_url.setGeometry(QtCore.QRect(129, 70, 471, 21))
        self.way_url.setStyleSheet("background-color:rgb(150,150,150);\n"
"color:white;\n"
"border: none;\n"
"margin: 0px;\n"
"padding: 0px;\n"
"")
        self.way_url.setObjectName("way_url")
        self.check_way_url = QtWidgets.QCheckBox(self.centralwidget)
        self.check_way_url.setGeometry(QtCore.QRect(10, 70, 16, 21))
        self.check_way_url.setStyleSheet("background-color: rgba(50, 50, 50, 0);")
        self.check_way_url.setText("")
        self.check_way_url.setObjectName("check_way_url")
        self.add_comand = QtWidgets.QPushButton(self.centralwidget)
        self.add_comand.setGeometry(QtCore.QRect(530, 210, 71, 21))
        self.add_comand.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.add_comand.setStyleSheet("color:white;\n"
"background-color: rgba(50, 50, 50, 150);\n"
"border: none;\n"
"margin: 0px;\n"
"padding: 0px;\n"
"")
        self.add_comand.setObjectName("add_comand")
        self.exit = QtWidgets.QPushButton(self.centralwidget)
        self.exit.setGeometry(QtCore.QRect(10, 210, 71, 23))
        self.exit.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.exit.setStyleSheet("color:white;\n"
"background-color: rgba(50, 50, 50, 150);\n"
"border: none;\n"
"margin: 0px;\n"
"padding: 0px;\n"
"")
        self.exit.setObjectName("exit")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(30, 100, 91, 21))
        self.label_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_4.setStyleSheet("color:white;\n"
"background-color: rgba(50, 50, 50, 150);\n"
"border: none;\n"
"margin: 0px;\n"
"padding: 0px;\n"
"")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.check_python = QtWidgets.QCheckBox(self.centralwidget)
        self.check_python.setGeometry(QtCore.QRect(10, 100, 16, 21))
        self.check_python.setStyleSheet("background-color: rgba(50, 50, 50, 0);")
        self.check_python.setText("")
        self.check_python.setObjectName("check_python")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(130, 100, 471, 101))
        self.textEdit.setStyleSheet("background-color:rgb(150,150,150);\n"
"color:white;\n"
"border: none;\n"
"margin: 0px;\n"
"padding: 0px;\n"
"")
        self.textEdit.setObjectName("textEdit")
        Tools.setCentralWidget(self.centralwidget)

        self.retranslateUi(Tools)
        QtCore.QMetaObject.connectSlotsByName(Tools)

    def retranslateUi(self, Tools):
        _translate = QtCore.QCoreApplication.translate
        Tools.setWindowTitle(_translate("Tools", "Tools Valentina"))
        self.comand_voice.setText(_translate("Tools", "Открой файл\\Включи музыку"))
        self.label.setText(_translate("Tools", "Название команды"))
        self.way_file_tool.setText(_translate("Tools", "..."))
        self.label_2.setText(_translate("Tools", "Путь к файлу"))
        self.way_file.setText(_translate("Tools", "C:\\Users\\Desktop"))
        self.label_3.setText(_translate("Tools", "URL ссылка"))
        self.way_url.setText(_translate("Tools", "https:\\\\www.youtube.com"))
        self.add_comand.setText(_translate("Tools", "Добавить"))
        self.exit.setText(_translate("Tools", "Выйти"))
        self.label_4.setText(_translate("Tools", "Python"))
        self.textEdit.setHtml(_translate("Tools", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">print(&quot;Hello world&quot;)</p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_Tools()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
